repos:
  - repo: local
    hooks:
      - id: codex-merge-clean
        name: codex-merge-clean
        entry: bash 0-tests/codex-merge-clean.sh
        language: script
        pass_filenames: true
        files: ''
    hooks:
      - id: pytest
        name: pytest
        entry: bash -c 'PYTHONPATH=. pytest -q'
        language: system
        types: [python]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.0
    hooks:
      - id: ruff
        args: [--fix]
  - repo: https://github.com/psf/black
    rev: 25.1.0
    hooks:
      - id: black
  - repo: https://github.com/koalaman/shellcheck
    rev: v0.9.0
    hooks:
      - id: shellcheck
        files: '\.(sh)$'
    


