name: CI

on:
  pull_request:
  push:

jobs:
  lint-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: changed
        uses: tj-actions/changed-files@v35
        with:
          files: |
            **/*.py
            **/*.sh
            **/*.js
            **/*.ts
            **/*.yaml
      - uses: actions/setup-python@v4
        if: steps.changed.outputs.any_changed == 'true'
        with:
          python-version: '3.11'
      - name: Install deps
        if: steps.changed.outputs.any_changed == 'true'
        run: |
          pip install pre-commit
      - name: Run pre-commit
        if: steps.changed.outputs.any_changed == 'true'
        run: pre-commit run --show-diff-on-failure --color always --files ${{ steps.changed.outputs.all_changed_files }}
      - name: Skip checks
        if: steps.changed.outputs.any_changed == 'false'
        run: echo "Documentation-only change; skipping checks."
